### ISSUE TITLE
Conta corrente - despesas para o calendário

### ISSUE THREAD

**Issue by msramalho** [msramalho/SigTools#21]
meter as que aparecem por saldar com o dropdown lá

**Comment by fabiodrg666** [comment]
Adeus juros de mora! :tada: 
Infelizmente não tenho nada em atrasado para implementar e testar isto.

**Comment by msramalho** [comment]
Pois, também terei de esperar pelo próximo pagamento, o próximo a ter implementa isto 😛

**Comment by msramalho** [comment]
meanwhile, isto pode ser fechado, não?
