### ISSUE TITLE
make pictures of people downloadable

### ISSUE THREAD

**Issue by msramalho** [msramalho/SigTools#22]
possibly with a simple overlayed btn

**Comment by msramalho** [comment]
Há pouco tive de fazer download de uma foto e é bastante fácil (right click -> download) pelo que não sei se isto seria assim tão útil. Como estavas a pensar fazer, @fabiodrg666?

**Comment by fabiodrg666** [comment]
Pois, há pouco também me lembrei disso e me questionei até que ponto isto é útil. Mas pronto, implementei em f603f25f, que apenas se aplica na página de perfil.

**Comment by msramalho** [comment]
Mudei para esse branch para testar, mas não sei se já está visual, consegues meter aqui um print?

**Comment by fabiodrg666** [comment]
Deste reload à extensão?
![image](https://user-images.githubusercontent.com/5472505/42843871-46d96232-8a09-11e8-851d-20683f1c88c6.png)

**Comment by msramalho** [comment]
Tinha dado, mas não aparecia isso. Parece-me fixe! 
Que achas então da forma de proceder?

**Comment by msramalho** [comment]
Era a tal ideia de usar a [contacts API](https://developers.google.com/contacts/v3/) mas acho que isto pode ficar postponed para quando houver tempo, por não ser prioritário.

**Comment by fabiodrg666** [comment]
Alright, concordo. Depois seria interessante integrar APIs de calendários, que já é um objetivo antigo, mas de facto não é prioritário.
