### ISSUE TITLE
[RIP] school calendar para fcup + fep + flup + fpceup + icbas

### ISSUE THREAD

**Issue by msramalho** [msramalho/SigTools#28]
decidiram inventar [um novo estilo](https://sigarra.up.pt/fcup/pt/web_base.gera_pagina?p_pagina=1035529)

**Comment by fabiodrg666** [comment]
Qual é a ideia para isto? Há alguns eventos que podem fazer sentido adicionar ao calendário. No caso da FEUP, há o *dia da FEUP*, *semana da FEUP*, etc etc. Itens como quando é que começa a época de exames, ou quando acabam as aulas, etc. acho que são redundantes porque à partida adiciona-se as aulas e exames individualmente. Só quero entender melhor a tua ideia para isto :) Seria para cada item ter opção de meter no calendário ou fazer algo mais inteligente?

**Comment by msramalho** [comment]
Isto está a funcionar no branch [school calendar](https://github.com/msramalho/SigToCa/tree/school_calendar) mas eu fiz para a feup e up ao mesmo tempo, depois é que me apercebi que para todas as outras faculdades não funcionava (ou eram pdfs ou o formato era diferente (os diferentes são os do título do issue)).
funciona [no da feup], por exemplo.

**Comment by msramalho** [comment]
mas como cada um decidiu inventar por si, e como isto não é uma cena assim tão importante eu decidi que não ia fazer mais porque me aborrecia, e tinha de tar a meter cada um dos casos no [school_calendar.js](https://github.com/msramalho/SigToCa/blob/school_calendar/js/extractors/school_calendar.js)... acho que não é algo vital e podemos deixar para já (a não ser que queiras mesmo fazer 😝)
