### ISSUE TITLE
Investigate exceptions thrown under options page

### ISSUE THREAD

**Issue by fabiodrg666** [msramalho/SigTools#29]
I was working on options page and noticed two exceptions are thrown. I think they were introduced with library extractor.

**Comment by msramalho** [comment]
will. look into it when possible

**Comment by fabiodrg666** [comment]
Fixed it. Basically the error was happening in `attachIfPossible()` for extractors using third-party libs which aren't imported in the `options.html`. Because there's nothing to attach on options page, I added an `if` statement to only run `attachIfPossible()` outside `options.html`. Not the fanciest solution, but better that importing unnecessary libs and running code without any need.
