### ISSUE TITLE
Improve dropdown under events list

### ISSUE THREAD

**Issue by fabiodrg666** [msramalho/SigTools#31]
When the modal containing events is short in height, the dropdown content isn't easily reachable. Instead of showing top-most, it hides and enables y-scrolling. Maybe we can improve this?
# Current
![screenshot_2018-09-07_00-14-25](https://user-images.githubusercontent.com/5472505/45189935-3e1d8b80-b233-11e8-8fd3-01a49cb1b84d.png)
# Suggestion
![screenshot_2018-09-07_00-16-01](https://user-images.githubusercontent.com/5472505/45189936-3e1d8b80-b233-11e8-91ba-f3a27eea1bec.png)

**Comment by msramalho** [comment]
Yup, I actually thought i had done already 🤔 
In any case, if you already have a solution with `min-height` or similar, just go ahead and commit 😄

**Comment by fabiodrg666** [comment]
What I did was setting `position: relative`, but I doubt that's the correct approach. Ahhh, CSS.. :nauseated_face: :joy:

**Comment by msramalho** [comment]
> In CSS, the correct approach is the one that works

**Comment by msramalho** [comment]
ok, my first thought was to play around with `min-height` and `display`

**Comment by fabiodrg666** [comment]
I will give it a try, thanks for the tip :)

**Comment by msramalho** [comment]
I also tried z-index to some extent with very little results... beacuse it means changing `position` and that also breaks some stuff
