### ISSUE TITLE
Add suport for events without start/due date

### ISSUE THREAD

**Issue by fabiodrg666** [msramalho/SigTools#32]
There's an issue with the `bills` extractor because in some cases, like students who applied to scholarships, don't have a due date to pay certain bills.

The following functions must be adapted to generate URLs without start and/or end date. The exception is thrown when calling `toGCalendar()` method.

- [x] `eventToGCalendar()`
- [x] `eventToOutlookCalendar()`
- [x] `eventToYahooCalendar()` **not tested**
- [x] ICS

**Comment by msramalho** [comment]
can you provide a print of the exception? is it undefined vars? probably those cases should prompt the user for a date, or use today's date and let them define it in the calendar apps. Because events without dates make little sense...
What do you think?

**Comment by fabiodrg666** [comment]
The exception is because `event.to` and `event.from` become `undefined`, thus the method `toGCalendar()` is not defined.

I am testing with undefined dates (the query parameters would be omitted or the values would be empty), I am assuming each Calendar website will automatically set to today's date. If that doesn't work, because the parameters might be required (not optional), then setting to today's date seems a good idea.

On the other hand... you are right, events without due dates don't make sense... :upside_down_face:. Hmm, I don't know, should the extension avoid attaching dropdowns on these bills?

**Comment by msramalho** [comment]
I won't be able to do this in the near future, but maybe there could be something in those functions, or even in the extractor class method that does something like:
`event. to = event. to || undefined`

**Comment by fabiodrg666** [comment]
On the extractor side I define those properties as empty strings, `''`. I was going to use `null` or `undefined`, but that would cause issues. `jQuery.extend` ignores `null` or `undefined` properties, and it's used in `_getConvertedToUri` to clone the `event` object. I could implement a recursive method to clone objects, but.. I am lazy :smile: 

So far is working for Outlook and Google. If `event.to` or `event.from` is an empty string, it omits the respective query parameters. Both platforms assume the today's date and the user can customize. I will implement for Yahoo. Do you have an account for testing?

**Comment by msramalho** [comment]
alright, if it works with empty string, even better.
I may have, but again I will only be able to do it, tomorrow or the day after.

**Comment by fabiodrg666** [comment]
@msramalho any progress in testing Yahoo?

**Comment by msramalho** [comment]
Just did and it is A-OK!!
