### ISSUE TITLE
Support events recurrence

### ISSUE THREAD

**Issue by fabiodrg666** [msramalho/SigTools#36]
This might be a problem. Moodle creates a single event, considered the parent, and then creates single events for each time the parent event re-occurs. The events are linked, through an `id`, but I am not sure if it's possible to get the recurrence pattern. :disappointed:

**Comment by fabiodrg666** [comment]
Fetching data for a single event, using `core_calendar_get_calendar_event_by_id`, doesn't provide recurrence details either.

**Comment by fabiodrg666** [comment]
Hmmm when we click to edit some event, there's a request to `core_get_fragment`. The response is html and javascript for generating the modal below.
![image](https://user-images.githubusercontent.com/5472505/45591400-90ecf680-b949-11e8-9c4f-4d30801e0831.png)

Maybe parsing the html could help in finding the recurrence pattern. Just another server request.
![image](https://media.giphy.com/media/NTur7XlVDUdqM/giphy.gif)

**Comment by fabiodrg666** [comment]
Uh, it's easier than I thought :man_facepalming: 
Moodle only supports weekly recurrence. Basically you can only set how many times the event should re-occur and that information is available from the server request's response I am using right now, `core_calendar_get_calendar_monthly_view`. I thought moodle would allow more advanced recurrence...

**Comment by msramalho** [comment]
Maybe they will, but while they don't, we don't care about it 🎈

**Comment by fabiodrg666** [comment]
Fixed 6624d89
