### ISSUE TITLE
button to download all moodle files at once

### ISSUE THREAD

**Issue by msramalho** [msramalho/SigTools#46]

**Comment by fabiodrg666** [comment]
Not sure if this is enable for all courses, but there's a built-in option for that. Clicking on it will redirect to a page to select the files intended for download

![image](https://user-images.githubusercontent.com/5472505/51023250-5f460e00-157e-11e9-9252-f11ce06851f4.png)

**Comment by msramalho** [comment]
just a prettier button xD
