### ISSUE TITLE
Add support for lack of event's location

### ISSUE THREAD

**Issue by fabiodrg** [msramalho/SigTools#48]
Not sure, but I think all extractors in Sigarra have some sort of location, typically a classroom. However, that assumption isn't verified in Moodle, and as a workaround the current location is Moodle. Would be nice to handle this more properly. 

The Google Calendars link and Outlook don't require the location parameter. The standard for ICS almost sure it doesn't require it either, although not sure if the library we are using has limitations.

**Comment by msramalho** [comment]
I don't think it has that limitation. In any case, one could always change it to `""`.

I believe I left it as `"Moodle"` in lack of something more informative as, for instance, some events are like homework on moodle, exam on moodle, delivery on moodle, ...

**Comment by fabiodrg666** [comment]
Ok, that makes some sense. Maybe this could be a setting in the options page?

**Comment by msramalho** [comment]
Agreed, and that should be straightforward to implement!
