### ISSUE TITLE
Timetable import file (.ics) shows an error when importing

### ISSUE THREAD

**Issue by imnotteixeira** [msramalho/SigTools#52]
Downloaded the .ics file to import in google calendar, but an error was thrown saying that only 1 of 13 events were loaded. I, then deleted that event (it was one of the multiple weekly classes) and re-imported, having 0 events imported.

## SOLUTION

To solve this error, one must replace the UID of **_ALL_** the events in the .ics file, adding a 'X' like so: 

As is: `UID:0@default`

To be:  `UID:X0@default`

source: http://nocurve.com/2018/03/14/importing-an-ics-file-to-google-calendar/

> I think other alpha-numeric values can be used instead of  'X' but I'm not sure.

If this can be patched in the .ics file generator, great, if not, I hope this helps!

**Comment by msramalho** [comment]
Hey @imnotteixeira, thanks for the issue, I had some feedback of people who had trouble doing this but managed the second time around. 

In any case, this helps and we"ll try to patch and test it as well. I am unable to do so for a few days, but will ASAP. If you feel adventurous you can also try to hammer some code :wink:

Also, can you give your browser details? name, version,...

**Comment by fabiodrg666** [comment]
Nice catch @imnotteixeira, I am also able to reproduce in Google calendar.

After investigating for a while, it seems **adding the "X" is not a permanent solution**. The `UID` is a global identifier,  if two events have the same `UID` in the same calendar there's a collision. Some calendar services like Outlook (which I use) seem to handle this, while Google and probably many others don't.

The standard suggests the following format for UID: `<date-time>@<domain>`:
- `date-time` is the current timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) when the event is created
- `domain` is typically the website domain which generates the calendar. It could be an IP address as well. The idea is to make the `UID` the most unique as possible. We could use `SigTools` in my opinion.

Regarding solutions for this problem, the library being used doesn't allow a custom UID, there are two-three issues open asking it, but so far there's no implementation. I will give it a try.

**Comment by fabiodrg666** [comment]
An interesting note regarding this UID. I have implemented the UID following the standard recommendation. For example, an event created today (15.Feb) at 22h53 would have an UID `20190215T225328-0@sigtools`. If multiple events are present in the same ical the digit following the dash is incremented, ensuring each `VEVENT` has a unique UID. I have been testing in Google Calendar and I noticed that if you import events with the same UID but with different data (summary, description, ...) the original imported event is updated with information from the latest event. Which makes sense. I am wondering if we can take advantage from this in SigTools.

**Comment by fabiodrg666** [comment]
I just found out I am not able to import calendars in Google Chrome v72 (Linux). A javascript exception is thrown in Google Calendar's code. Interestingly, in Firefox it works smoothly. I also tried with ical files from other sources and they are not working. Not sure if this only happens on my side or it's affecting multiple users. Nevertheless, it's an issue on Google's side, I would say.

**Comment by msramalho** [comment]
@imnotteixeira we believe it is fixed, but you can further test it if you have the opportunity, thanks again!
