### ISSUE TITLE
sigarra statistics not showing if our name is different from the one on the grade sheet

### ISSUE THREAD

**Issue by mehr-licht** [msramalho/SigTools#60]
If our _'autenticacao-nome'_ is different from the one that appears on the grade sheet, if we edit our public name to display only two names instead of the whole name, SigTools can't find us on the grade sheet and don't display any statistics regarding _our_  grade.
All Sigarra pages displays a thumbnail of our photo at the top and its url has our student code in it: 
```html
<img src="fotografias_service.foto_thumb?pct_cod=201607946" class="autenticacao-foto">
```
If you could change the way it gets our grade to find by our student code instead of full name (or student code if there is no match with the full name), the problem should be solved.

**Comment by msramalho** [comment]
Great catch @mehr-licht, it's one of those things we would hardly come across. We will fix this for the following release, thanks!
