### ISSUE TITLE
Add suport for resources reservations

### ISSUE THREAD

**Issue by fabiodrg** [msramalho/SigTools#71]
Sigarra has a page for resource reservations. I am not aware of resources types available for teachers, but students can reserve rooms in the library (6th floor). I think it's useful to implement an extractor for those reservations.
- Present the _Add to calendar_ button after a successful reservation
- Support the page of all future reservations available here: https://sigarra.up.pt/feup/pt/res_recursos_geral.pedidos_tipo_grp

**Comment by msramalho** [comment]
closes 71 was a typo and has been updated to 70

**Comment by msramalho** [comment]
this PR is WIP but has a close commit, which is the right state?

**Comment by fabiodrg666** [comment]
@msramalho It lacks support for another page where it lists all reservations. For now, it only supports the reservation submission page. I have some work done locally, just need to refactor and add documentation where needed
