### ISSUE TITLE
`npm run dist` does not work but `npm run build` + `npm run zip` does

### ISSUE THREAD

**Issue by msramalho** [msramalho/SigTools#76]
I was unable to understand why, but the zip command only works properly if executed individually, otherwise only the manifest file is copied to the zipped versions.

**Comment by fabiodrg** [comment]
It seems the problem has to do with pipes being async. By the time the `mergeAll` returns, not all pipes are completed. Experiment: 
```
function mergeAll(done) {
    pipe(...);
    pipe(...);
    ...
    setTimeout(function () {
        done()
    }, 5000);
}
```
The delay of 5 seconds before `done()` ensures all buffers and streams flushed (i.e. the destination files are created).
Not sure how to solve it, but will try to use Promises API.

**Comment by fabiodrg** [comment]
After inspecting in more detail, I think the most sensible option is to separate each move command (coping files from `src/` to `build/`) to individual Gulp tasks.

I didn't find a method that lets return multiple streams. As per Gulp, a task can only return one stream. Moreover, I suspect Gulp uses synchronous Node.js streams, which don't allow me to use a `Promisse.all()` to handle all promises at once. Therefore, I would have to add event handlers to capture the stream closing/finishing, increment some counter, and when the counter is `N`, then all streams are flushed and the task can conclude.
```js
const t1 = pipe('./src/css/**/*', `./build/${target}/css`);
t1.on('finish', () => console.log('Finish'));
...
```
That versus individual tasks per copy/move operation that can run in parallel, I think the latter is more sensible to be compliant with Gulp, faster to code and easier to read.
